/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generated from the docs/ folder structure.
  // Each folder becomes a sidebar category (using its _category_.json
  // for label + position), each .md/.mdx file becomes a page
  // (using its frontmatter for label + sidebar_position).
  // No manual list to maintain — new folders and files just appear.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
